application:
  title: "sicad-backend"
  version: "1.0.0"

spring:
  banner:
    location: banner.txt
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: ${APP_ENV}
